version: "3"
services:
  angular-cli: 
    build: 
      context: ../../builds/angular-cli
    command: bash
    volumes:
      - ../../src:/app
  antivirus:
    healthcheck:
      test: ["CMD", "./check.sh"]
      interval: 60s
      retries: 3
      start_period: 120s