version: "3"
services:
  angular-cli: 
    build: 
      context: ../../builds/angular-cli
    command: bash
    volumes:
      - ../../src:/app
  pyruiz: 
    build: 
      context: ../../builds/pyruiz
    command: python3 app.py
    volumes:
      - ../../src/pyruiz:/dat
  