version: "3"
services:
  frontend:
    build: 
      context: ../../builds/angular-cli
    command: 
      - ng
      - serve
      - --open
      - --watch
      - --host
      - 0.0.0.0
    volumes:
      - ../../src/frontend:/app
    ports:
      - 4200:4200
  backend-legacy:
    build:
      context: ../../builds/php-gd
  microservice-a: 
    build:
      context: ../../builds/nestjs-cli
  mongo:
    build: 
      context: ../../builds/mongo
  antivirus:
    build:
      context: ../../builds/antivirus
    restart: unless-stopped
    volumes:
      - clam:/var/lib/clamav
    ports:
      - 3310:3310
      # - 4201:4200
volumes:
  clam:

